-include $(OCAMLPRO)/ocpp/Makefile
-include $(OCAMLPRO)/sempatch/Makefile
-include $(OCAMLPRO)/maker/Makefile
-include $(OCAMLPRO)/ocpwin/Makefile
-include $(OCAMLPRO)/utils/Makefile

COMP_OCP=$(OCPP_CMOS) $(SEMPATCH_CMOS) $(MAKER_CMOS)

