
val ext_cc_obj : string
        (* Extension for object files generated by C compiler *)
val executable_name: string
        (* Absolute name of the currently running executable.
           More precise than Sys.executable_name *)

       (* Should detect MSVC directories on Windows *)
val detect_msvc : string ref

(* The OS type of the host target (à la Sys.os_type) *)
val os_type : string

(* for ocamlmklib *)
val bindir : string
val supports_shared_libraries : bool
val mksharedlib : string
val byteccrpath : string
val nativeccrpath : string
val mksharedlibrpath : string
val mklib1 : string
val mklib2 : string
