

# These files are included in utils/config.mlp and utils/config.mli
utils/config.cmi: $(OCAMLPRO)/utils/config.mli
utils/config.cmo: $(OCAMLPRO)/utils/config.ml
utils/config.cmx: $(OCAMLPRO)/utils/config.ml
